### ISSUE TITLE
Docs about CircularBuffer seem to be wrong

### ISSUE THREAD

**Issue by reidevries** [pingdynasty/OwlProgram#104]
![2021-11-12T19:52:11,387464545+10:30](https://user-images.githubusercontent.com/25862413/141443939-16e70cc3-a1b0-40ae-b498-3829e796768f.png)

> Circular buffer that keeps a delta table of differences for faster fractional delay lines.
> 
> Note that this class requires twice as much buffer space as

These lines seem to be wrong and I'm not familiar with Doxygen so I can't tell where it is pulling this documentation from. `CircularBuffer.h` doesn't seem to keep a delta table of differences at all. Is this a planned feature or just a mistake?

**Comment by reidevries** [comment]
upon further inspection, looks like these lines were intended for `FractionalCircularBuffer.h` instead. I noticed these lines in that file:
```
/**
 * Circular buffer that keeps a delta table of differences for faster fractional delay lines.
 * Note that this class requires twice as much buffer space as @class CircularBuffer.
 */
```
 
 As i said I'm not familiar with Doxygen, but perhaps it's seeing `@class CircularBuffer` and thinking that this comment must be attached to `CircularBuffer`

**Comment by antisvin** [comment]
@reidevries, you're correct and Doxygen is wrong! It looks like it somehow uses child class documentation for parent class, very strange. We should probably just write documentation for CircularBuffer to avoid this, or maybe try building docs with newer version of Doxygen.

**Comment by reidevries** [comment]
I just tried removing the word `@class` from that doc comment, and it now seems to generate the correct docs. It even links to the CircularBuffer page correctly!

**Comment by antisvin** [comment]
And those classes aren't even related. So yes, their docs say:
```
Here the special command \class is used to indicate that the comment block contains documentation for the class Test. 
```
\class and @class mean the same thing, in this case it assigns documentation to class rather than just creates a link. We should probably be using @link for that, thanks for pointing out this issue.

**Comment by pingdynasty** [comment]
okay, weird!
Good find @reidevries and thanks for letting us know
