### ISSUE TITLE
kiss fft source files need to be added to Libraries and Makefile

### ISSUE THREAD

**Issue by giuliomoro** [pingdynasty/OwlProgram#14]
Otherwise you will not be able to compile without the -DARM_CORTEX flag!

**Comment by giuliomoro** [comment]
Still kiss_fft needs to be added to the OBJS and includes in the Makefile so that a patch can be built for the Owl when removing -DARM_CORTEX, e.g. for testing purposes

**Comment by pingdynasty** [comment]
done commit 3721e5d0
