### ISSUE TITLE
Add switch in the Makefile to force non-arm when make run

### ISSUE THREAD

**Issue by giuliomoro** [pingdynasty/OwlProgram#18]
That is enable to remove the -DARM_CORTEX flag when building for Owl without having to edit the makefile
Useful for testing purposes

**Comment by pingdynasty** [comment]
Test non-arm on a non-arm platform, e.g web

**Comment by giuliomoro** [comment]
If I test it on a non-arm platform I cannot compare performances!

**Comment by pingdynasty** [comment]
no need

On 07/07/15 00:14, giuliomoro wrote:

> If I test it on a non-arm platform I cannot compare performances!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pingdynasty/OwlProgram/issues/18#issuecomment-119024754.

## 

Martin Klang
Alpha Plus Technology Ltd
London UK
