### ISSUE TITLE
After ComplexFourierTest has been running for a while, the output becomes loud and distorted

### ISSUE THREAD

**Issue by giuliomoro** [pingdynasty/OwlProgram#19]
Output becomes noise and or distorted. ...?

When this happens the stats remain unchanged
  Device stats: CPU: 43% Stack: 592 Heap: 4096

This does NOT fix it:
  make PATCHNAME=ComplexFourierTransformTest run
this DOES fix it:
  reboot the owl and 
  make PATCHNAME=ComplexFourierTransformTest run

Note: if after a failure you make another patch, its output will still be distorted. Need to reboot the owl to fix it

**Comment by pingdynasty** [comment]
fixed?
