### ISSUE TITLE
make web error: "symbol multiply defined!"

### ISSUE THREAD

**Issue by giuliomoro** [pingdynasty/OwlProgram#20]
$ make web
Building patch Template
emcc -fno-rtti -fno-exceptions  -IOwlPatches -ISource -I./PatchSource -I./LibSource -I./Build -I./TestPatches -ILibraries/KissFFT -s EXPORTED_FUNCTIONS="['_WEB_setup','_WEB_setParameter','_WEB_processBlock','_WEB_getPatchName','_WEB_getParameterName','_WEB_getMessage','_WEB_getStatus']" Source/PatchProgram.cpp Source/PatchProcessor.cpp Source/operators.cpp Source/message.cpp  WebSource/web.cpp  ./LibSource/basicmaths.c ./LibSource/StompBox.cpp ./LibSource/FloatArray.cpp ./LibSource/ComplexFloatArray.cpp  ./PatchSource/kiss_fft.c  Libraries/KissFFT/kiss_fft.c -o ./Build/patch.js
/usr/bin/llvm-link: link error in '/tmp/tmp2f1eiN/kiss_fft_10.o': Linking globals named 'kiss_fft_alloc': symbol multiply defined!
Traceback (most recent call last):
  File "/usr/bin/emcc", line 1778, in <module>
    shared.Building.link(linker_inputs, in_temp(target_basename + '.bc'), force_archive_contents = len(filter(lambda temp: not temp.endswith(STATICLIB_ENDINGS), temp_files)) == 0)
  File "/usr/share/emscripten/tools/shared.py", line 1146, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error: 
make: **\* [web] Error 1

**Comment by pingdynasty** [comment]
remove the kiss_fft files from your PatchSource directory, you are
including them twice:
`./PatchSource/kiss_fft.c Libraries/KissFFT/kiss_fft.c`

**Comment by giuliomoro** [comment]
that solves it
