### ISSUE TITLE
Implement envelope classes

### ISSUE THREAD

**Issue by ghost** [pingdynasty/OwlProgram#25]
Would be good to have a couple of classes for simple envelopes: AR, ASR and ADSR.
The interface should ideally be suitable for both sample- and block-based processing, e.g.

```
class SomeEnvelope {
 void setAttack(float);
 void setRelease(float);
 void trigger();
 void release();
 // or perhaps better :
 void setStage(SomeEnvelopeStageEnum stage);
 float process(float); // increments envelope one step
 void process(FloatArray buf); // increments envelope by buf.length
};
```

To figure out the best interface it'd be good to write a demo patch, or adapt an existing one.
You could take an oscillator from here and make it trigger (at blockrate) on `isButtonPressed(PUSHBUTTON)`
http://hoxtonowl.com/patch-library/patch/Morphing_Oscillator/

**Comment by pingdynasty** [comment]
@giuliomoro I've grabbed your Envelope.hpp, modified it, and checked in to master.
https://github.com/pingdynasty/OwlProgram/blob/master/LibSource/Envelope.hpp

Trigger and re-trigger modes not fully tested.

**Comment by giuliomoro** [comment]
I fixed the trigger in 4e33dbba3c5746dbcd893e5cfea36998068c8c62
What is "retrigger" supposed to do ?

**Comment by pingdynasty** [comment]
Misunderstanding: trigger runs the entire envelope, not just AR. Only difference to gate is that it doesn't abort during Attack.
Retrigger restarts the envelope after Release, making it LFO.

**Comment by giuliomoro** [comment]
Well I can see if you want the trigger to be be ADR but it could never be ADSR as it would not know how long the S should be!
So retrigger should set a flag. We should change the interface to  setRetrigger(bool retrigger)
sounds good ?

```
  From: Martin Klang <notifications@github.com>
```

 To: pingdynasty/OwlProgram OwlProgram@noreply.github.com 
Cc: giuliomoro giuliomoro@yahoo.it
 Sent: Friday, 27 November 2015, 8:58
 Subject: Re: [OwlProgram] Implement envelope classes (#25)

Misunderstanding: trigger runs the entire envelope, not just AR. Only difference to gate is that it doesn't abort during Attack.
Retrigger restarts the envelope after Release, making it LFO.—

**Comment by giuliomoro** [comment]
closed  895bb74

**Comment by ghost** [comment]
what's the purpose of the changes?

Martin

**Comment by giuliomoro** [comment]
Previous version was broken:
- it would hang on the sustain stage when using trigger() and 
- when set to retrigger, it would run in a loop, regardless of new triggers coming in. Now a new trigger coming in while in retrigger mode will reset the envelope as expected
