### ISSUE TITLE
Emscripten config file

### ISSUE THREAD

**Issue by sam-artuso** [pingdynasty/OwlProgram#26]
Could you add the ability for the Makefile to pass the `--em-config` argument to Emscripten? I don't feel familiar enough with makefiles to do it myself.

Explainer: this argument enables me to specify where emcc should look for its configuration file. If not specified, it will default to `~/.emscripten`. However, for security reasons my API runs as the `nobody` user, that has no home directory, so this file cannot be found.

**Comment by ghost** [comment]
You could try without editing the Makefile
It contains this directive:
`EMCCFLAGS ?= -fno-rtti -fno-exceptions`
this means that if EMCCFLAGS is not specified, assign the value.

So what you can do, is pass in
`EMCCFLAGS="--em-config emcc.cfg -fno-rtti -fno-exceptions"`
ie prepend your options to the variable.

**Comment by sam-artuso** [comment]
I did that, but it seems to me that all the flags at lines 112-115 [1] are now ignored? Or am I doing something wrong?

My `make` invokation now looks like:

```
make EMCCFLAGS="--em-config /opt/.emscripten -fno-rtti -fno-exceptions" BUILD='/tmp/owl-build-MCEcPM' PATCHSOURCE='/tmp/owl-src-KNIrLP' PATCHNAME='Overdrive' PATCHIN=2 PATCHOUT=2 PATCHFILE='OverdrivePatch.hpp' PATCHCLASS='OverdrivePatch' minify
```

[1] https://github.com/pingdynasty/OwlProgram/blob/master/Makefile#L112-L115

**Comment by ghost** [comment]
oh.
my `emcc --help` says:
`
--em-config If not specified, the environment variable EM_CONFIG is read for this
                   file, and if that is not set, the default location
                   ~/.emscripten is assumed.
`
Can you try setting EM_CONFIG?

**Comment by sam-artuso** [comment]
Something like this?
 EM_CONFIG=/opt/.emscripten make ...

**Comment by ghost** [comment]
yes that should work
