### ISSUE TITLE
Implement FIR class

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlProgram#4]

**Comment by pingdynasty** [comment]
https://www.keil.com/pack/doc/CMSIS/DSP/html/group___f_i_r.html
arm_fir_f32 ()

**Comment by giuliomoro** [comment]
Done, commit bf5950d263c98cd8e813e0570ea0f5cb4d9a5ad8
Performance:
49% with a 128-taps
89% with a 256-taps

**Comment by giuliomoro** [comment]
THe current implementation is ARM only, we need a multiplatform implementation as well
