### ISSUE TITLE
Linking-time errors with `make test`

### ISSUE THREAD

**Issue by giuliomoro** [pingdynasty/OwlProgram#45]
Both with llvm/gcc and gcc/gcc

**Comment by giuliomoro** [comment]
So I tried e.g.:

```
git checkout master
make realclean
make TEST=ShortArrayTest test
```

and I get 

```
Undefined symbols for architecture i386:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [test] Error 1
make: *** [test] Error 2
```

it is strange, because `main` is defined in `PatchTest.cpp` which is being compiled by `make test`.

Can you reproduce this issue?

This is Mac with `gcc/llvm`

**Comment by giuliomoro** [comment]
but it works fine with the actual `gcc/gcc` installed via macports.
Any reason why gcc/llvm should fail with the above error?

**Comment by giuliomoro** [comment]
Got it. It is the `-ffreestanding` option that makes gcc/llvm fail at linking time in `make test`

**Comment by pingdynasty** [comment]
uh, really? is that an llvm thing?

**Comment by giuliomoro** [comment]
I have no idea, but removing it fixed it.

**Comment by pingdynasty** [comment]
I guess we don't need `-ffreestanding`  for tests, or even `-fno-builtin`

**Comment by giuliomoro** [comment]
I guess we don't need it. Also a nice addition would be something like this in `test.mk`

```
-CC=$(TOOLROOT)gcc
-LD=$(TOOLROOT)gcc
+CCOMPILER?=gcc
+CXXCOMPILER?=g++
+CC=$(TOOLROOT)$(CCOMPILER)
+LD=$(TOOLROOT)$(CCOMPILER)
```

because when building natively, your compiler of choice may not be in a TOOLROOT or may not even be called gcc. In the case of gcc installed by macports, for instance, it is called `gcc-mp-49`

**Comment by pingdynasty** [comment]
Yes the definitions in `test.mk` were probably quick and dirty. But might as well just define `CC=gcc`, the `TOOLROOT` thing is really redundant here. I think those are probably the default CC and CXX definitions anyhow, apart from using gcc for LD which again is incorrect in this context.
Does it work if you get rid of the lot?

**Comment by giuliomoro** [comment]
> But might as well just define CC=gcc, 

very right!

So I can compile with the "stock" `test.mk` with:

```
make test TEST=ShortArrayTest -j6  CXX=g++-mp-4.9
```

**Comment by giuliomoro** [comment]
Incidentally, passing these flags to gcc/llvm will make the test compile and link
`-ffreestanding -Wl,-no_new_main -Wl,-e,__Z4mainiPPc`
but then it segfaults.

I don't want to know more about this.
