### ISSUE TITLE
Test Biquad

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlProgram#5]
Coefficient calculators currently don't take into account the effects of multiple stages on fc and gain/q.

**Comment by pingdynasty** [comment]
It would be ideal if when you have created an N stage  filter and call e.g. setLowPass(fc, q), that the resulting cascaded filter will have a combined fc and q which matches the parameters passed in.
In other words, adjusted for multiple stages.

**Comment by giuliomoro** [comment]
http://www.earlevel.com/main/2016/09/29/cascading-filters/

**Comment by pingdynasty** [comment]
Ooh nice. I like Nigel Redmon!

The calculator JS is here
http://www.earlevel.com/scripts/widgets/20160929/CombiningBiquads.js

But what about when we don't want a Butterworth response?
