### ISSUE TITLE
When "make run": Leaked objects detected

### ISSUE THREAD

**Issue by benzkji** [pingdynasty/OwlProgram#60]
Building (make patch) works without errors/assertion failures.

make run is saying this: 

    Building patch AuxSend
    Sending patch AuxSend to OWL-MIDI to run
    JUCE v3.2.0
    *** Leaked objects detected: 1 instance(s) of class MidiOutputDevice
    JUCE Assertion failure in juce_LeakedObjectDetector.h:95
    *** Leaked objects detected: 1 instance(s) of class MidiOutput
    JUCE Assertion failure in juce_LeakedObjectDetector.h:95
    *** Leaked objects detected: 1 instance(s) of class Thread
    JUCE Assertion failure in juce_LeakedObjectDetector.h:95
    *** Leaked objects detected: 2 instance(s) of class WaitableEvent
    JUCE Assertion failure in juce_LeakedObjectDetector.h:95

having a look with OwlControl seems everything worked fine. Juce problem?

**Comment by pingdynasty** [comment]
The messages come from [FirmwareSender ](https://github.com/pingdynasty/FirmwareSender)and can be safely ignore (but should be fixed).

**Comment by pingdynasty** [comment]
I created an issue there: https://github.com/pingdynasty/FirmwareSender/issues/1
