### ISSUE TITLE
make store doesnt seem to work

### ISSUE THREAD

**Issue by benzkji** [pingdynasty/OwlProgram#61]
on ubuntu zesty/17. tried with gcc 6.3.0 and 5.4.1. FirmwareSender and OwlControl compiled with gcc 5.4.1.

I can build (make patch) and run (make run) patches. When trying to store (make store) a patch on the owl, everything looks (almost) fine:

    Building patch OctaveDown
    Sending patch OctaveDown to OWL-MIDI to store in slot 1
    JUCE v3.2.0
    *** Leaked objects detected: 1 instance(s) of class MidiOutputDevice
    JUCE Assertion failure in juce_LeakedObjectDetector.h:95
    *** Leaked objects detected: 1 instance(s) of class MidiOutput
    JUCE Assertion failure in juce_LeakedObjectDetector.h:95
    *** Leaked objects detected: 1 instance(s) of class Thread
    JUCE Assertion failure in juce_LeakedObjectDetector.h:95
    *** Leaked objects detected: 2 instance(s) of class WaitableEvent
    JUCE Assertion failure in juce_LeakedObjectDetector.h:95

But the patch is not stored. And, "Template" is selected as current patch, when checking with OwlControl.

**Comment by benzkji** [comment]
Actually, it works. But. The patch name is always "Template". And, SLOT=0 seems to store in position 37, SLOT=1 in position 38, etc.

Info from OwlControl, when launched from CLI (own patch, stored in SLOT=0):

    preset name 37: Template
    parameter name 0: Send
    parameter name 1: 
    parameter name 2: AutoLevel
    parameter name 3: Return / Mix
    parameter name 4: ExPedal Send
    preset name 0: AuxSend

Or, OctaveDown, from pingdynasty/OwlPatches (SLOT=1)

    preset name 38: Template
    parameter name 0: Dry
    parameter name 1: Octave 1
    parameter name 2: Octave 2
    preset name 0: OctaveDown

I dont get the logic here? Is OwlProgram made to store "User Patches" from slot 37 on upwards? Or is something wrong? At least, it seems it needs some explenations in the readme?

Thanks bringing light into this ;-)

**Comment by pingdynasty** [comment]
Yes agreed, this should be better documented! I'll try to get it done on Monday.

When changing which patch you are compiling you need to do a `make clean`, otherwise the name is recycled from the previous compilation. I'd like to fix this issue in the Makefile, but haven't found a good solution yet.

The four user slots are numbered 0-3 by the FirmwareSender (the utility used to create and upload the sysex). In the OWL firmware, these four patches get placed at the end, so they become patch number 37 to 40.

**Comment by benzkji** [comment]
THX! Is there a way to store more than four Patches that are not from the firmware?

**Comment by pingdynasty** [comment]
Not at the moment, the only way is to recompile the firmware with the patches you want.
There is work under way on making all slots user writeable.

**Comment by pingdynasty** [comment]
Redundant by flash storage in OpenWare
