### ISSUE TITLE
Project documentation missing information

### ISSUE THREAD

**Issue by ykmm** [pingdynasty/OwlProgram#64]
Hi,

having received the Magus last week (YES!), I started putting together the build environment, and I had to look a lot in the code to figure out what was needed and how should it be used.

At the moment I was able to compile PD and C++ patches successfully, no luck with faust or max ones.

Would it be ok If I did a pull request to start adding some of this in the Readme.txt to:

- fix/add some details
- show how to prepare a build environment on ubuntu 18.04 (I could do that for other debian based oses, it just happened that I started with that one)

I want to also be able to compile max and faust patches, and for those I'll open other github issues, but that's for a little later on.

**Comment by pingdynasty** [comment]
yes please, PRs are always appreciated!

**Comment by pingdynasty** [comment]
Docs are now here: https://www.openwarelab.org/
