### ISSUE TITLE
Fast math functions disabled

### ISSUE THREAD

**Issue by antisvin** [pingdynasty/OwlProgram#67]
I've noticed that some stuff is not using optimizations from fast math functions. I.e. V/oct control on audio rate was using 20% CPU on Magus.

Here's what causing it:
https://github.com/pingdynasty/OwlProgram/blob/master/LibSource/basicmaths.h#L107-L109

Apparently __FAST_MATH__ is first undefined, then used as the flag for enabling fast math - so those optimizations are never enabled. Not sure how  that happened, but it seems like aliases to fast functions should be defined unconditionally.

**Comment by ghost** [comment]
Yes you are correct, and I don't know how this happened either! Will do 
an update as soon as possible - thanks!


Martin
